/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `award_categories`
--

DROP TABLE IF EXISTS `award_categories`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `award_categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `award_type_id` int(11) NOT NULL,  
  `name` varchar(255) DEFAULT NULL,
  `description` text,
  PRIMARY KEY (`id`),
   KEY `index_award_categories_on_award_type_id` (`award_type_id`) 
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `award_categories`
--

LOCK TABLES `award_categories` WRITE;
/*!40000 ALTER TABLE `award_categories` DISABLE KEYS */;
INSERT INTO `award_categories` (`id`,`award_type_id`,`name`, `description`) VALUES 
(1,1,'Best Movie','This is Best Movie Award'),
(2,1,'Best Director','This is Best Director Award'),
(3,1,'Best Actor','This is Best Actor Award'),
(4,1,'Best Actress','This is Best Actress Award'),
(5,1,'Best Supporting Actor','This is Best Supporting Actor Award'),
(6,1,'Best Supporting Actress','This is Best Supporting Actress Award'),
(7,1,'Best Performance in a Negative Role','This is Best Performance in a Negative Role Award'),
(8,1,'Best Performance in a Comic Role','This is Best Performance in a Comic Role Award'),
(9,1,'Best Male Debut','This is Best Male Debut Award'),
(10,1,'Best Female Debut','This is Best Female Debut Award'),
(11,1,'Best Music Director','This is Best Music Director Award'),
(12,1,'Best Lyricist','This is Best Lyricist Award'),
(13,1,'Best Male Playback Singer','This is Best Male Playback Singer Award'),
(14,1,'Best Female Playback Singer','This is Best Female Playback Singer Award'),
(15,1,'Critics Award Best Movie','This is Critics Award Best Movie Award'),
(16,1,'Critics Award Best Performance - Actor','This is Critics Award Best Performance - Actor Award'),
(17,1,'Critics Award Best Performance - Actress','This is Critics Award Best Performance - Actress Award'),
(18,1,'Best Documentary','This is Best Documentary Award'),
(19,1,'Best Story','This is Best Story Award'),
(20,1,'Best Screenplay','This is Best Screenplay Award'),
(21,1,'Best Dialogue','This is Best Dialogue Award'),
(22,1,'Best Action','This is Best Action Award'),
(23,1,'Best Art Direction','This is Best Art Direction Award'),
(24,1,'Best Background Score','This is Best Background Score Award'),
(25,1,'Best Cinematography','This is Best Cinematography Award'),
(26,1,'Best Editing','This is Best Editing Award'),
(27,1,'Best Choreography','This is Best Choreography Award'),
(28,1,'Best Sound Recording','This is Best Sound Recording Award'),
(29,1,'Best Special Effects','This is Best Special Effects Award'),
(30,1,'Best Costume Design','This is Best Costume Design Award'),
(31,1,'Lifetime Achievement','This is Lifetime Achievement Award'),
(32,1,'Power Award','This is Power Award Award'),
(33,1,'Special Performance Award','This is Special Performance Award Award'),
(34,1,'Best Scene of the Year','This is Best Scene of the Year Award'),
(35,1,'RD Burman Award for New Music Talent','This is RD Burman Award for New Music Talent Award'),
(36,1,'Best Film of 50 Years','This is Best Film of 50 Years Award'),
(37,2,'Best Film','This is Best Film Award'),
(38,2,'Best Director','This is Best Director Award'),
(39,2,'Best Actor','This is Best Actor Award'),
(40,2,'Best Actress','This is Best Actress Award'),
(41,2,'Best Supporting Actor','This is Best Supporting Actor Award'),
(42,2,'Best Supporting Actress','This is Best Supporting Actress Award'),
(43,2,'Best Villain','This is Best Villain Award'),
(44,2,'Best Comedian','This is Best Comedian Award'),
(45,2,'Best Music Director','This is Best Music Director Award'),
(46,2,'Best Lyricist','This is Best Lyricist Award'),
(47,2,'Best Male Playback','This is Best Male Playback Award'),
(48,2,'Best Female Playback','This is Best Female Playback Award'),
(49,2,'Most Promising Newcomer - Male','This is Most Promising Newcomer - Male Award'),
(50,2,'Most Promising Newcomer - Female','This is Most Promising Newcomer - Female Award'),
(51,2,'Best Art Direction','This is Best Art Direction Award'),
(52,2,'Best Action','This is Best Action Award'),
(53,2,'Best Cinematography','This is Best Cinematography Award'),
(54,2,'Best Editing','This is Best Editing Award'),
(55,2,'Best Choreography','This is Best Choreography Award'),
(56,2,'Best Background Music','This is Best Background Music Award'),
(57,2,'Best Story','This is Best Story Award'),
(58,2,'Best Screenplay','This is Best Screenplay Award'),
(59,2,'Best Dialogue','This is Best Dialogue Award'),
(60,2,'Best Sound Recording','This is Best Sound Recording Award'),
(61,2,'Lifetime Achievement','This is Lifetime Achievement Award'),
(62,2,'Jodi No. 1','This is Jodi No. 1 Award'),
(63,2,'Best Actress (Popular Choice)','This is Best Actress (Popular Choice) Award'),
(64,2,'Best Actor (Popular Choice)','This is Best Actor (Popular Choice) Award'),
(65,2,'Best Actor (Critics)','This is Best Actor (Critics) Award'),
(66,2,'Best Actress (Critics)','This is Best Actress (Critics) Award'),
(67,2,'Best Child Artist ','This is Best Child Artist  Award'),
(68,2,'Special Jury Award ','This is Special Jury Award  Award'),
(69,2,'Entertainer of the Year','This is Entertainer of the Year Award'),
(70,2,'Best Animation Film','This is Best Animation Film Award'),
(71,2,'Best Film in English','This is Best Film in English Award'),
(72,2,'Star Screen Award Best Jodi of Decade','This is Star Screen Award Best Jodi of Decade Award'),
(73,2,'Showman of the Millennium','This is Showman of the Millennium Award'),
(74,3,'Best Film','This is Best Film Award'),
(75,3,'Best Director','This is Best Director Award'),
(76,3,'Best Actor','This is Best Actor Award'),
(77,3,'Best Actress','This is Best Actress Award'),
(78,3,'Best Track of the Year','This is Best Track of the Year Award'),
(79,3,'Best Actor (Critics)','This is Best Actor (Critics) Award'),
(80,3,'Best Actress (Critics)','This is Best Actress (Critics) Award'),
(81,3,'Best Supporting Actor','This is Best Supporting Actor Award'),
(82,3,'Best Supporting Actress','This is Best Supporting Actress Award'),
(83,3,'Best Villain','This is Best Villain Award'),
(84,3,'Best Comedian','This is Best Comedian Award'),
(85,3,'Most Promising Director','This is Most Promising Director Award'),
(86,3,'Best Male Debut','This is Best Male Debut Award'),
(87,3,'Best Female Debut','This is Best Female Debut Award'),
(88,3,'Best Male Playback Singer','This is Best Male Playback Singer Award'),
(89,3,'Best Female Playback Singer','This is Best Female Playback Singer Award'),
(90,3,'Best Music Director','This is Best Music Director Award'),
(91,3,'Best Lyricist','This is Best Lyricist Award'),
(92,3,'Lifetime Achievement','This is Lifetime Achievement Award'),
(93,3,'Best Background Music','This is Best Background Music Award'),
(94,3,'Best Dialogue','This is Best Dialogue Award'),
(95,3,'Best Story','This is Best Story Award'),
(96,3,'Best Screenplay','This is Best Screenplay Award'),
(97,3,'Best Cinematography','This is Best Cinematography Award'),
(98,3,'Best Editing','This is Best Editing Award'),
(99,3,'Best Action','This is Best Action Award'),
(100,3,'Best Art Direction','This is Best Art Direction Award'),
(101,3,'Best Audiography','This is Best Audiography Award'),
(102,3,'Best Choreography','This is Best Choreography Award'),
(103,3,'Best Costumes','This is Best Costumes Award'),
(104,3,'Best Film Processing','This is Best Film Processing Award'),
(105,3,'Best Publicity','This is Best Publicity Award'),
(106,3,'Best Song Recording','This is Best Song Recording Award'),
(107,3,'Best Visual Effects','This is Best Visual Effects Award'),
(108,3,'Lux Face of the Year','This is Lux Face of the Year Award'),
(109,3,'Netizen Award Best Film','This is Netizen Award Best Film Award'),
(110,3,'Premiere Choice - Female','This is Premiere Choice - Female Award'),
(111,3,'Premiere Choice - Male','This is Premiere Choice - Male Award'),
(112,3,'Special Award for Debut Director','This is Special Award for Debut Director Award'),
(113,3,'Special Award for Hall of Fame','This is Special Award for Hall of Fame Award'),
(114,3,'Special Award for Outstanding Contribution to International Cinema','This is Special Award for Outstanding Contribution to International Cinema Award'),
(115,3,'Special Award for Outstanding Performance - Female','This is Special Award for Outstanding Performance - Female Award'),
(116,3,'Special Award for Outstanding Performance - Male','This is Special Award for Outstanding Performance - Male Award'),
(117,3,'Queen of Hearts','This is Queen of Hearts Award'),
(118,3,'Dynamic Duo','This is Dynamic Duo Award'),
(119,3,'True Indian Beauty','This is True Indian Beauty Award'),
(120,3,'Superstar of the Year - Female','This is Superstar of the Year - Female Award'),
(121,3,'Superstar of the Year - Male','This is Superstar of the Year - Male Award'),
(122,3,'Zenith Power Team Award','This is Zenith Power Team Award Award'),
(123,3,'Best Contribution to Indian Cinema','This is Best Contribution to Indian Cinema Award'),
(124,3,'Golden Grade Award','This is Golden Grade Award Award'),
(125,3,'Forever Diva Award','This is Forever Diva Award Award'),
(126,3,'Special Recognition','This is Special Recognition Award'),
(127,3,'Fun Cinema Entertainer of the year','This is Fun Cinema Entertainer of the year Award'),
(128,3,'Queen of Bollywood','This is Queen of Bollywood Award'),
(129,3,'British Indian Actor Award','This is British Indian Actor Award Award'),
(130,3,'Zee Icon award','This is Zee Icon award Award'),
(131,3,'Zee Cinema Entertainer of the year','This is Zee Cinema Entertainer of the year Award'),
(132,4,'Best Movie','This is Best Movie Award'),
(133,4,'Best Director','This is Best Director Award'),
(134,4,'Best Actor','This is Best Actor Award'),
(135,4,'Best Actress','This is Best Actress Award'),
(136,4,'Best Supporting Actor','This is Best Supporting Actor Award'),
(137,4,'Best Supporting Actress','This is Best Supporting Actress Award'),
(138,4,'Best Performance in a Negative Role','This is Best Performance in a Negative Role Award'),
(139,4,'Best Performance in a Comic Role','This is Best Performance in a Comic Role Award'),
(140,4,'Best Music Director','This is Best Music Director Award'),
(141,4,'Best Lyricist','This is Best Lyricist Award'),
(142,4,'Best Playback Singer Male','This is Best Playback Singer Male Award'),
(143,4,'Best Playback Singer Female','This is Best Playback Singer Female Award'),
(144,4,'Style Icon of the Year','This is Style Icon of the Year Award'),
(145,4,'Style Diva of the Year','This is Style Diva of the Year Award'),
(146,4,'Glamorous Star Award','This is Glamorous Star Award Award'),
(147,4,'Star Debut Award','This is Star Debut Award Award'),
(148,4,'Face of the Year','This is Face of the Year Award'),
(149,4,'Special Award for Global Impact','This is Special Award for Global Impact Award'),
(150,4,'Outstanding Contribution to Indian cinema','This is Outstanding Contribution to Indian cinema Award'),
(151,4,'Outstanding Achievement in Indian cinema','This is Outstanding Achievement in Indian cinema Award'),
(152,4,'Outstanding Achievement by an Indian in International Cinema','This is Outstanding Achievement by an Indian in International Cinema Award'),
(153,4,'Artists of the Decade','This is Artists of the Decade Award'),
(154,4,'Best Art Direction','This is Best Art Direction Award'),
(155,4,'Best Action','This is Best Action Award'),
(156,4,'Best Background Score','This is Best Background Score Award'),
(157,4,'Best Cinematography','This is Best Cinematography Award'),
(158,4,'Best Choreography','This is Best Choreography Award'),
(159,4,'Best Costume Design','This is Best Costume Design Award'),
(160,4,'Best Dialogue','This is Best Dialogue Award'),
(161,4,'Best Editing','This is Best Editing Award'),
(162,4,'Best Makeup','This is Best Makeup Award'),
(163,4,'Best Screenplay','This is Best Screenplay Award'),
(164,4,'Best Sound Recording','This is Best Sound Recording Award'),
(165,4,'Best Sound Re-Recording','This is Best Sound Re-Recording Award'),
(166,4,'Best Special Effects','This is Best Special Effects Award'),
(167,4,'Best Story','This is Best Story Award'),
(168,5,'Best Feature Film','This is Best Feature Film Award'),
(169,5,'Best Direction','This is Best Direction Award'),
(170,5,'Best Popular Film Providing Wholesome Entertainment','This is Best Popular Film Providing Wholesome Entertainment Award'),
(171,5,'Best Childrens Film','This is Best Childrens Film Award'),
(172,5,'Indira Gandhi Award for Best First Film of a Director','This is Indira Gandhi Award for Best First Film of a Director Award'),
(173,5,'Best Actor','This is Best Actor Award'),
(174,5,'Best Actress','This is Best Actress Award'),
(175,5,'Best Supporting Actor','This is Best Supporting Actor Award'),
(176,5,'Best Supporting Actress','This is Best Supporting Actress Award'),
(177,5,'Best Child Artist','This is Best Child Artist Award'),
(178,5,'Nargis Dutt Award for Best Feature Film on National Integration','This is Nargis Dutt Award for Best Feature Film on National Integration Award'),
(179,5,'Second Best Feature Film','This is Second Best Feature Film Award'),
(180,5,'Best Cinematography','This is Best Cinematography Award'),
(181,5,'Best Screenplay','This is Best Screenplay Award'),
(182,5,'Best Art Direction','This is Best Art Direction Award'),
(183,5,'Best Make-up Artist','This is Best Make-up Artist Award'),
(184,5,'Best Costume Design','This is Best Costume Design Award'),
(185,5,'Best Music Direction','This is Best Music Direction Award'),
(186,5,'Best Lyrics','This is Best Lyrics Award'),
(187,5,'Best Male Playback Singer','This is Best Male Playback Singer Award'),
(188,5,'Best Female Playback Singer','This is Best Female Playback Singer Award'),
(189,5,'Best Choreography','This is Best Choreography Award'),
(190,5,'Best Audiography','This is Best Audiography Award'),
(191,5,'Best Editing','This is Best Editing Award'),
(192,5,'Best Special Effects','This is Best Special Effects Award'),
(193,5,'Special Jury Award / Special Mention (Feature Film)','This is Special Jury Award / Special Mention (Feature Film) Award'),
(194,5,'Best Film on Other Social Issues','This is Best Film on Other Social Issues Award'),
(195,5,'Best Film on Family Welfare','This is Best Film on Family Welfare Award'),
(196,5,'Best Film on Environment Conservation/Preservation','This is Best Film on Environment Conservation/Preservation Award'),
(197,5,'Best Feature Film in Assamese','This is Best Feature Film in Assamese Award'),
(198,5,'Best Feature Film in Bengali','This is Best Feature Film in Bengali Award'),
(199,5,'Best Feature Film in Hindi','This is Best Feature Film in Hindi Award'),
(200,5,'Best Feature Film in Kannada','This is Best Feature Film in Kannada Award'),
(201,5,'Best Feature Film in Konkani','This is Best Feature Film in Konkani Award'),
(202,5,'Best Feature Film in Malayalam','This is Best Feature Film in Malayalam Award'),
(203,5,'Best Feature Film in Manipuri','This is Best Feature Film in Manipuri Award'),
(204,5,'Best Feature Film in Marathi','This is Best Feature Film in Marathi Award'),
(205,5,'Best Feature Film in Oriya','This is Best Feature Film in Oriya Award'),
(206,5,'Best Feature Film in Punjabi','This is Best Feature Film in Punjabi Award'),
(207,5,'Best Feature Film in Tamil','This is Best Feature Film in Tamil Award'),
(208,5,'Best Feature Film in Telugu','This is Best Feature Film in Telugu Award'),
(209,5,'Best Feature Film in English','This is Best Feature Film in English Award'),
(210,5,'Best Feature Film in Bhojpuri','This is Best Feature Film in Bhojpuri Award'),
(211,5,'Best Feature Film in Kokborok','This is Best Feature Film in Kokborok Award'),
(212,5,'Best Feature Film in Monpa','This is Best Feature Film in Monpa Award'),
(213,5,'Best Feature Film in Tulu','This is Best Feature Film in Tulu Award'),
(214,5,'Dadasaheb Phalke Lifetime Achievement','This is Dadasaheb Phalke Lifetime Achievement Award'),
(215,5,'Best Non-Feature Film','This is Best Non-Feature Film Award'),
(216,5,'Best First Non-Feature Film','This is Best First Non-Feature Film Award'),
(217,5,'Best Anthropological/Ethnographic Film','This is Best Anthropological/Ethnographic Film Award'),
(218,5,'Best Biographical Film','This is Best Biographical Film Award'),
(219,5,'Best Arts/Cultural Film','This is Best Arts/Cultural Film Award'),
(220,5,'Best Scientific Film','This is Best Scientific Film Award'),
(221,5,'Best Promotional Film','This is Best Promotional Film Award'),
(222,5,'Best Agriculture Film','This is Best Agriculture Film Award'),
(223,5,'Best Film on Social Issues','This is Best Film on Social Issues Award'),
(224,5,'Best Educational/Motivational/Instructional Film','This is Best Educational/Motivational/Instructional Film Award'),
(225,5,'Best Environment/Conservation/Preservation Film','This is Best Environment/Conservation/Preservation Film Award'),
(226,5,'Best Exploration/Adventure Film','This is Best Exploration/Adventure Film Award'),
(227,5,'Best Investigative Film','This is Best Investigative Film Award'),
(228,5,'Best Animated Film','This is Best Animated Film Award'),
(229,5,'Best Short Fiction Film','This is Best Short Fiction Film Award'),
(230,5,'Best Non-Feature Film on Family Welfare','This is Best Non-Feature Film on Family Welfare Award'),
(231,5,'Best Non-Feature Film Direction','This is Best Non-Feature Film Direction Award'),
(232,5,'Best Non-Feature Film Cinematography','This is Best Non-Feature Film Cinematography Award'),
(233,5,'Best Non-Feature Film Audiography','This is Best Non-Feature Film Audiography Award'),
(234,5,'Best Non-Feature Film Editing','This is Best Non-Feature Film Editing Award'),
(235,5,'Best Non-Feature Film Music Direction','This is Best Non-Feature Film Music Direction Award'),
(236,5,'Special Jury Award / Special Mention (Non-Feature Film)','This is Special Jury Award / Special Mention (Non-Feature Film) Award'),
(237,5,'Best Book on Cinema','This is Best Book on Cinema Award'),
(238,5,'Best Film Critic','This is Best Film Critic Award');


/*!40000 ALTER TABLE `award_categories` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2011-05-14 21:01:46
