/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `awards`
--

DROP TABLE IF EXISTS `awards`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `awards` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type_id` int(11),
  `type_name` varchar(255) DEFAULT NULL,  
  `name` varchar(255) DEFAULT NULL,
  `description` text,
  `recipient` int(11),
  PRIMARY KEY (`id`),
   KEY `index_award_on_type_id_and_type_name` (`type_id`,`type_name`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `awards`
--

LOCK TABLES `awards` WRITE;
/*!40000 ALTER TABLE `awards` DISABLE KEYS */;
INSERT INTO `awards` (`id`,`type_id`,`type_name`,`name`, `description`,`recipient`) VALUES 
(1,1,'Filmfare Award',"40 Years of Greatness Award","This is 40 Years of Greatness Award",1),
(2,1,'Filmfare Award',"Best Action Director","This is Best Action Director",1),
(3,1,'Filmfare Award',"Best Actor (Female)","This is Best Actor (Female)",1),
(4,1,'Filmfare Award',"Best Actor (Male)","This is Best Actor (Male)",1),
(5,1,'Filmfare Award',"Best Actor In a Comic Role","This is Best Actor In a Comic Role",1),
(6,1,'Filmfare Award',"Best Actor In a Negative Role","This is Best Actor In a Negative Role",1),
(7,1,'Filmfare Award',"Best Actor In a Supporting Role (Female)","This is Best Actor In a Supporting Role (Female)",1),
(8,1,'Filmfare Award',"Best Actor In a Supporting Role (Male)","This is Best Actor In a Supporting Role (Male)",1),
(9,1,'Filmfare Award',"Best Art Direction (Black And White)","This is Best Art Direction (Black And White)",2),
(10,1,'Filmfare Award',"Best Art Direction","This is Best Art Direction",2),
(11,1,'Filmfare Award',"Best Background Music","This is Best Background Music",1),
(12,1,'Filmfare Award',"Best Choreography","This is Best Choreography",1),
(13,1,'Filmfare Award',"Best Cinematography (Black And White)","This is Best Cinematography (Black And White)",2),
(14,1,'Filmfare Award',"Best Cinematography (Colour)","This is Best Cinematography (Colour)",2),
(15,1,'Filmfare Award',"Best Cinematography","This is Best Cinematography",2),
(16,1,'Filmfare Award',"Best Costume Design","This is Best Costume Design",2),
(17,1,'Filmfare Award',"Best Debut (Female)","This is Best Debut (Female)",1),
(18,1,'Filmfare Award',"Best Debut (Male)","This is Best Debut (Male)",1),
(19,1,'Filmfare Award',"Best Debutant Director","This is Best Debutant Director",1),
(20,1,'Filmfare Award',"Best Dialogue","This is Best Dialogue",2),
(21,1,'Filmfare Award',"Best Director","This is Best Director",1),
(22,1,'Filmfare Award',"Best Editing","This is Best Editing",2),
(23,1,'Filmfare Award',"Best Film Of Fifty Years","This is Best Film Of Fifty Years",2),
(24,1,'Filmfare Award',"Best Film","This is Best Film",2),
(25,1,'Filmfare Award',"Best Lyrics","This is Best Lyrics",1),
(26,1,'Filmfare Award',"Best Music","This is Best Music",1),
(27,1,'Filmfare Award',"Best Playback Singer (Female)","This is Best Playback Singer (Female)",1),
(28,1,'Filmfare Award',"Best Playback Singer (Male)","This is Best Playback Singer (Male)",1),
(29,1,'Filmfare Award',"Best Production Design","This is Best Production Design",2),
(30,1,'Filmfare Award',"Best Scene Of The Year","This is Best Scene Of The Year",2),
(31,1,'Filmfare Award',"Best Screenplay","This is Best Screenplay",2),
(32,1,'Filmfare Award',"Best Sound Design","This is Best Sound Design",2),
(33,1,'Filmfare Award',"Best Sound Recording","This is Best Sound Recording",2),
(34,1,'Filmfare Award',"Best Special Effects","This is Best Special Effects",2),
(35,1,'Filmfare Award',"Best Story","This is Best Story",2),
(36,1,'Filmfare Award',"Best Visual Effects","This is Best Visual Effects",2),
(37,1,'Filmfare Award',"Critics Award - Best Actor","This is Critics Award - Best Actor",1),
(38,1,'Filmfare Award',"Critics Award - Best Actress","This is Critics Award - Best Actress",1),
(39,1,'Filmfare Award',"Critics Award For Best Feature Film","This is Critics Award For Best Feature Film",2),
(40,1,'Filmfare Award',"Face Of The Year","This is Face Of The Year",1),
(41,1,'Filmfare Award',"Lifetime Achievement Award","This is Lifetime Achievement Award",1),
(42,1,'Filmfare Award',"Look Of The Year","This is Look Of The Year",1),
(43,1,'Filmfare Award',"Most Promising Newcomer (Female)","This is Most Promising Newcomer (Female)",1),
(44,1,'Filmfare Award',"Most Promising Newcomer (Male)","This is Most Promising Newcomer (Male)",1),
(45,1,'Filmfare Award',"New Face Of The Year","This is New Face Of The Year",1),
(46,1,'Filmfare Award',"Outstanding Performance Of The Year (Male)","This is Outstanding Performance Of The Year (Male)",1),
(47,1,'Filmfare Award',"Powerhouse Award","This is Powerhouse Award",1),
(48,1,'Filmfare Award',"R. D. Burman Award","This is R. D. Burman Award",1),
(49,1,'Filmfare Award',"Special Award","This is Special Award",1),
(50,1,'Filmfare Award',"Special Jury Award","This is Special Jury Award",1),
(51,1,'Filmfare Award',"Special Jury Recognition","This is Special Jury Recognition",1),
(52,1,'Filmfare Award',"Special Performance Awards","This is Special Performance Awards",1),
(53,1,'Filmfare Award',"Special Veterans Award","This is Special Veterans Award",1),
(54,2,'Star Screen Award',"Best Action Director","This is Best Action Director",1),
(55,2,'Star Screen Award',"Best Actor (Female)","This is Best Actor (Female)",1),
(56,2,'Star Screen Award',"Best Actor (Male)","This is Best Actor (Male)",1),
(57,2,'Star Screen Award',"Best Actor In a Comic Role (Female)","This is Best Actor In a Comic Role (Female)",1),
(58,2,'Star Screen Award',"Best Actor In a Comic Role (Male)","This is Best Actor In a Comic Role (Male)",1),
(59,2,'Star Screen Award',"Best Actor In a Negative Role (Female)","This is Best Actor In a Negative Role (Female)",1),
(60,2,'Star Screen Award',"Best Actor In a Negative Role (Male)","This is Best Actor In a Negative Role (Male)",1),
(61,2,'Star Screen Award',"Best Actor In a Supporting Role (Female)","This is Best Actor In a Supporting Role (Female)",1),
(62,2,'Star Screen Award',"Best Actor In a Supporting Role (Male)","This is Best Actor In a Supporting Role (Male)",1),
(63,2,'Star Screen Award',"Best Animation Film","This is Best Animation Film",2),
(64,2,'Star Screen Award',"Best Art Direction","This is Best Art Direction",2),
(65,2,'Star Screen Award',"Best Background Music","This is Best Background Music",2),
(66,2,'Star Screen Award',"Best Cast","This is Best Cast",2),
(67,2,'Star Screen Award',"Best Child Artiste","This is Best Child Artiste",1),
(68,2,'Star Screen Award',"Best Choreography","This is Best Choreography",1),
(69,2,'Star Screen Award',"Best Cinematography","This is Best Cinematography",2),
(70,2,'Star Screen Award',"Best Costume Design","This is Best Costume Design",2),
(71,2,'Star Screen Award',"Best Dialogue","This is Best Dialogue",2),
(72,2,'Star Screen Award',"Best Diaspora Film On An Indian Subject Made By NRI","This is Best Diaspora Film On An Indian Subject Made By NRI",2),
(73,2,'Star Screen Award',"Best Diaspora Film","This is Best Diaspora Film",2),
(74,2,'Star Screen Award',"Best Director - Special Jury Award","This is Best Director - Special Jury Award",1),
(75,2,'Star Screen Award',"Best Director","This is Best Director",1),
(76,2,'Star Screen Award',"Best Distributor","This is Best Distributor",2),
(77,2,'Star Screen Award',"Best Editing","This is Best Editing",2),
(78,2,'Star Screen Award',"Best Film","This is Best Film",2),
(79,2,'Star Screen Award',"Best Indian Film In English","This is Best Indian Film In English",2),
(80,2,'Star Screen Award',"Best Jodi of the Dacade Award","This is Best Jodi of the Dacade Award",1),
(81,2,'Star Screen Award',"Best Lyrics","This is Best Lyrics",1),
(82,2,'Star Screen Award',"Best Music","This is Best Music",1),
(83,2,'Star Screen Award',"Best Musical Debut Of The Year","This is Best Musical Debut Of The Year",2),
(84,2,'Star Screen Award',"Best Performance For An Indian Film In English","This is Best Performance For An Indian Film In English",2),
(85,2,'Star Screen Award',"Best Performer","This is Best Performer",1),
(86,2,'Star Screen Award',"Best Playback Singer (Female)","This is Best Playback Singer (Female)",1),
(87,2,'Star Screen Award',"Best Playback Singer (Male)","This is Best Playback Singer (Male)",1),
(88,2,'Star Screen Award',"Best Popular Actor Award","This is Best Popular Actor Award",1),
(89,2,'Star Screen Award',"Best Popular Actress Award","This is Best Popular Actress Award",1),
(90,2,'Star Screen Award',"Best Publicity Design","This is Best Publicity Design",2),
(91,2,'Star Screen Award',"Best Re-Recordist","This is Best Re-Recordist",2),
(92,2,'Star Screen Award',"Best Screenplay","This is Best Screenplay",2),
(93,2,'Star Screen Award',"Best Sound","This is Best Sound",2),
(94,2,'Star Screen Award',"Best Special Effects","This is Best Special Effects",2),
(95,2,'Star Screen Award',"Best Story","This is Best Story",2),
(96,2,'Star Screen Award',"Best Technical Debut","This is Best Technical Debut",2),
(97,2,'Star Screen Award',"Critics Award - Best Actress","This is Critics Award - Best Actress",1),
(98,2,'Star Screen Award',"Critics Choice","This is Critics Choice",1),
(99,2,'Star Screen Award',"Debut Producer - Special Jury Award","This is Debut Producer - Special Jury Award",2),
(100,2,'Star Screen Award',"Decade Honour","This is Decade Honour",1),
(101,2,'Star Screen Award',"Discovery Of The Year","This is Discovery Of The Year",1),
(102,2,'Star Screen Award',"Distinction In Acting","This is Distinction In Acting",1),
(103,2,'Star Screen Award',"Distinction In Directorial Debut","This is Distinction In Directorial Debut",1),
(104,2,'Star Screen Award',"Fun Cinema Entertainer of the year","This is Fun Cinema Entertainer of the year",1),
(105,2,'Star Screen Award',"Indian Film In English (Best Performance)","This is Indian Film In English (Best Performance)",2),
(106,2,'Star Screen Award',"Jodi No 1","This is Jodi No 1",1),
(107,2,'Star Screen Award',"Lifetime Achievement Award","This is Lifetime Achievement Award",1),
(108,2,'Star Screen Award',"Most Popular Music","This is Most Popular Music",2),
(109,2,'Star Screen Award',"Most Promising Debut Director","This is Most Promising Debut Director",1),
(110,2,'Star Screen Award',"Most Promising Newcomer (Female)","This is Most Promising Newcomer (Female)",1),
(111,2,'Star Screen Award',"Most Promising Newcomer (Male)","This is Most Promising Newcomer (Male)",1),
(112,2,'Star Screen Award',"New Musical Sensation - Female","This is New Musical Sensation - Female",1),
(113,2,'Star Screen Award',"Nokia Best New Talent - Music Award","This is Nokia Best New Talent - Music Award",1),
(114,2,'Star Screen Award',"Pioneering Effort In Mainstream Cinema (Animation)","This is Pioneering Effort In Mainstream Cinema (Animation)",1),
(115,2,'Star Screen Award',"Ramnath Goenka Memorial Award","This is Ramnath Goenka Memorial Award",1),
(116,2,'Star Screen Award',"Special Jury Award - Voice","This is Special Jury Award - Voice",1),
(117,2,'Star Screen Award',"Special Jury Award","This is Special Jury Award",1),
(118,2,'Star Screen Award',"Special Jury Awards For Spectacular Cutting Of Age Technology","This is Special Jury Awards For Spectacular Cutting Of Age Technology",1),
(119,2,'Star Screen Award',"Special Jury Mention","This is Special Jury Mention",1),
(120,2,'Star Screen Award',"Special Recognition For Breakthrough Performance","This is Special Recognition For Breakthrough Performance",1),
(121,2,'Star Screen Award',"Special Recognition For Significance Portrayal Of A Historical Figure","This is Special Recognition For Significance Portrayal Of A Historical Figure",1),
(122,2,'Star Screen Award',"Unsung Hero Award","This is Unsung Hero Award",1),
(123,3,'Zee Cine Award',"Best Action Director","This is Best Action Director",2),
(124,3,'Zee Cine Award',"Best Actor (Female)","This is Best Actor (Female)",1),
(125,3,'Zee Cine Award',"Best Actor (Male)","This is Best Actor (Male)",1),
(126,3,'Zee Cine Award',"Best Actor In a Comic Role","This is Best Actor In a Comic Role",1),
(127,3,'Zee Cine Award',"Best Actor In a Negative Role","This is Best Actor In a Negative Role",1),
(128,3,'Zee Cine Award',"Best Actor In a Supporting Role (Female)","This is Best Actor In a Supporting Role (Female)",1),
(129,3,'Zee Cine Award',"Best Actor In a Supporting Role (Male)","This is Best Actor In a Supporting Role (Male)",1),
(130,3,'Zee Cine Award',"Best Art Direction","This is Best Art Direction",2),
(131,3,'Zee Cine Award',"Best Audiography","This is Best Audiography",2),
(132,3,'Zee Cine Award',"Best Background Music","This is Best Background Music",2),
(133,3,'Zee Cine Award',"Best Choreography","This is Best Choreography",1),
(134,3,'Zee Cine Award',"Best Cinematography","This is Best Cinematography",2),
(135,3,'Zee Cine Award',"Best Costume Design","This is Best Costume Design",2),
(136,3,'Zee Cine Award',"Best Dialogue","This is Best Dialogue",2),
(137,3,'Zee Cine Award',"Best Director - Special Jury Award","This is Best Director - Special Jury Award",1),
(138,3,'Zee Cine Award',"Best Director","This is Best Director",1),
(139,3,'Zee Cine Award',"Best Editing","This is Best Editing",2),
(140,3,'Zee Cine Award',"Best Film Processing","This is Best Film Processing",2),
(141,3,'Zee Cine Award',"Best Film","This is Best Film",2),
(142,3,'Zee Cine Award',"Best Lifetime Jodi Award","This is Best Lifetime Jodi Award",1),
(143,3,'Zee Cine Award',"Best Lyrics","This is Best Lyrics",1),
(144,3,'Zee Cine Award',"Best Marketed Film","This is Best Marketed Film",2),
(145,3,'Zee Cine Award',"Best Music","This is Best Music",1),
(146,3,'Zee Cine Award',"Best Playback Singer (Female)","This is Best Playback Singer (Female)",1),
(147,3,'Zee Cine Award',"Best Playback Singer (Male)","This is Best Playback Singer (Male)",1),
(148,3,'Zee Cine Award',"Best Producer of the Year","This is Best Producer of the Year",2),
(149,3,'Zee Cine Award',"Best Publicity Design","This is Best Publicity Design",2),
(150,3,'Zee Cine Award',"Best Screenplay","This is Best Screenplay",2),
(151,3,'Zee Cine Award',"Best Song Recording","This is Best Song Recording",2),
(152,3,'Zee Cine Award',"Best Sound Design","This is Best Sound Design",2),
(153,3,'Zee Cine Award',"Best Sound Re-recording","This is Best Sound Re-recording",2),
(154,3,'Zee Cine Award',"Best Special Effects","This is Best Special Effects",2),
(155,3,'Zee Cine Award',"Best Story","This is Best Story",2),
(156,3,'Zee Cine Award',"Best Visual Effects","This is Best Visual Effects",2),
(157,3,'Zee Cine Award',"Bollywod Queen Award","This is Bollywod Queen Award",1),
(158,3,'Zee Cine Award',"British Indian Actor Award","This is British Indian Actor Award",1),
(159,3,'Zee Cine Award',"Critics Award - Best Actor","This is Critics Award - Best Actor",1),
(160,3,'Zee Cine Award',"Critics Award - Best Actress","This is Critics Award - Best Actress",1),
(161,3,'Zee Cine Award',"Critics Award - Best Film","This is Critics Award - Best Film",2),
(162,3,'Zee Cine Award',"Critics Special Award","This is Critics Special Award",1),
(163,3,'Zee Cine Award',"Dynamic Duo","This is Dynamic Duo",1),
(164,3,'Zee Cine Award',"Face Of The Year","This is Face Of The Year",1),
(165,3,'Zee Cine Award',"Forever Diva Award","This is Forever Diva Award",1),
(166,3,'Zee Cine Award',"Fun Cinema Entertainer of the year","This is Fun Cinema Entertainer of the year",1),
(167,3,'Zee Cine Award',"Hall Of Fame","This is Hall Of Fame",1),
(168,3,'Zee Cine Award',"International Female Icon","This is International Female Icon",1),
(169,3,'Zee Cine Award',"International Male Icon","This is International Male Icon",1),
(170,3,'Zee Cine Award',"Jury Award for Best Actor","This is Jury Award for Best Actor",1),
(171,3,'Zee Cine Award',"Jury Award for Best Actress","This is Jury Award for Best Actress",1),
(172,3,'Zee Cine Award',"Jury Award for Best Film","This is Jury Award for Best Film",2),
(173,3,'Zee Cine Award',"Lifetime Achievement Award","This is Lifetime Achievement Award",1),
(174,3,'Zee Cine Award',"Lux Face Of The Year","This is Lux Face Of The Year",1),
(175,3,'Zee Cine Award',"Male Superstar of the Year","This is Male Superstar of the Year",1),
(176,3,'Zee Cine Award',"Most Popular Track Of The Year","This is Most Popular Track Of The Year",2),
(177,3,'Zee Cine Award',"Most Promising Debut (Child Artiste)","This is Most Promising Debut (Child Artiste)",1),
(178,3,'Zee Cine Award',"Most Promising Debut (Female)","This is Most Promising Debut (Female)",1),
(179,3,'Zee Cine Award',"Most Promising Debut (Male)","This is Most Promising Debut (Male)",1),
(180,3,'Zee Cine Award',"Most Promising Debut Director","This is Most Promising Debut Director",1),
(181,3,'Zee Cine Award',"Outstanding Performance (Female)","This is Outstanding Performance (Female)",1),
(182,3,'Zee Cine Award',"Outstanding Performance (Male)","This is Outstanding Performance (Male)",1),
(183,3,'Zee Cine Award',"Queen Of Hearts Award","This is Queen Of Hearts Award",1),
(184,3,'Zee Cine Award',"Sa Re Ga Ma Pa - Song of the Year","This is Sa Re Ga Ma Pa - Song of the Year",2),
(185,3,'Zee Cine Award',"Special Award for International Cinema","This is Special Award for International Cinema",2),
(186,3,'Zee Cine Award',"Special Recognition","This is Special Recognition",1),
(187,3,'Zee Cine Award',"True Indian Actress","This is True Indian Actress",1),
(188,3,'Zee Cine Award',"Zee Cinema Entertainer of the year","This is Zee Cinema Entertainer of the year",1),
(189,3,'Zee Cine Award',"Zee Icon award","This is Zee Icon award",1),
(190,3,'Zee Cine Award',"Zenith Power Team Award","This is Zenith Power Team Award",1),
(191,4,'International Indian Film Academy (IIFA)',"Best Action Director","This is Best Action Director",2),
(192,4,'International Indian Film Academy (IIFA)',"Best Actor (Female)","This is Best Actor (Female)",1),
(193,4,'International Indian Film Academy (IIFA)',"Best Actor (Male)","This is Best Actor (Male)",1),
(194,4,'International Indian Film Academy (IIFA)',"Best Actor In a Comic Role","This is Best Actor In a Comic Role",1),
(195,4,'International Indian Film Academy (IIFA)',"Best Actor In a Negative Role","This is Best Actor In a Negative Role",1),
(196,4,'International Indian Film Academy (IIFA)',"Best Actor In a Supporting Role (Female)","This is Best Actor In a Supporting Role (Female)",1),
(197,4,'International Indian Film Academy (IIFA)',"Best Actor In a Supporting Role (Male)","This is Best Actor In a Supporting Role (Male)",1),
(198,4,'International Indian Film Academy (IIFA)',"Best Art Direction","This is Best Art Direction",2),
(199,4,'International Indian Film Academy (IIFA)',"Best Background Music","This is Best Background Music",2),
(200,4,'International Indian Film Academy (IIFA)',"Best Choreography","This is Best Choreography",1),
(201,4,'International Indian Film Academy (IIFA)',"Best Cinematography","This is Best Cinematography",2),
(202,4,'International Indian Film Academy (IIFA)',"Best Costume Design","This is Best Costume Design",2),
(203,4,'International Indian Film Academy (IIFA)',"Best Debut (Female)","This is Best Debut (Female)",1),
(204,4,'International Indian Film Academy (IIFA)',"Best Debut (Male)","This is Best Debut (Male)",1),
(205,4,'International Indian Film Academy (IIFA)',"Best Dialogue","This is Best Dialogue",2),
(206,4,'International Indian Film Academy (IIFA)',"Best Director","This is Best Director",1),
(207,4,'International Indian Film Academy (IIFA)',"Best Editing","This is Best Editing",2),
(208,4,'International Indian Film Academy (IIFA)',"Best Film","This is Best Film",2),
(209,4,'International Indian Film Academy (IIFA)',"Best Lyrics","This is Best Lyrics",1),
(210,4,'International Indian Film Academy (IIFA)',"Best Make-up Artist","This is Best Make-up Artist",2),
(211,4,'International Indian Film Academy (IIFA)',"Best Music","This is Best Music",1),
(212,4,'International Indian Film Academy (IIFA)',"Best Playback Singer (Female)","This is Best Playback Singer (Female)",1),
(213,4,'International Indian Film Academy (IIFA)',"Best Playback Singer (Male)","This is Best Playback Singer (Male)",1),
(214,4,'International Indian Film Academy (IIFA)',"Best Screenplay","This is Best Screenplay",2),
(215,4,'International Indian Film Academy (IIFA)',"Best Song Recording","This is Best Song Recording",2),
(216,4,'International Indian Film Academy (IIFA)',"Best Sound Re-recording","This is Best Sound Re-recording",2),
(217,4,'International Indian Film Academy (IIFA)',"Best Sound Recording","This is Best Sound Recording",2),
(218,4,'International Indian Film Academy (IIFA)',"Best Special Effects","This is Best Special Effects",2),
(219,4,'International Indian Film Academy (IIFA)',"Best Story","This is Best Story",2),
(220,4,'International Indian Film Academy (IIFA)',"Habitat For Humanity Ambassadorship","This is Habitat For Humanity Ambassadorship",1),
(221,4,'International Indian Film Academy (IIFA)',"IIFA Green Global Award","This is IIFA Green Global Award",1),
(222,4,'International Indian Film Academy (IIFA)',"IIFA outstanding contribution to Hindi Cineam (Female)","This is IIFA outstanding contribution to Hindi Cineam (Female)",1),
(223,4,'International Indian Film Academy (IIFA)',"IIFA outstanding contribution to Hindi Cineam (Male)","This is IIFA outstanding contribution to Hindi Cineam (Male)",1),
(224,4,'International Indian Film Academy (IIFA)',"Outstanding Achievement by an Indian Internationally","This is Outstanding Achievement by an Indian Internationally",1),
(225,5,'National Film Award',"Best Actor","This is Best Actor",1),
(226,5,'National Film Award',"Best Actress","This is Best Actress",1),
(227,5,'National Film Award',"Best Agricultural Film","This is Best Agricultural Film",2),
(228,5,'National Film Award',"Best Animation Film ( Documentary )","This is Best Animation Film ( Documentary )",2),
(229,5,'National Film Award',"Best Animation Film","This is Best Animation Film",2),
(230,5,'National Film Award',"Best Anthropological / Ethnographic Film","This is Best Anthropological / Ethnographic Film",2),
(231,5,'National Film Award',"Best Art Direction","This is Best Art Direction",2),
(232,5,'National Film Award',"Best Arts And Cultural Film","This is Best Arts And Cultural Film",2),
(233,5,'National Film Award',"Best Audiography","This is Best Audiography",2),
(234,5,'National Film Award',"Best Biographical / Historical Reconstruction / Compilation film","This is Best Biographical / Historical Reconstruction / Compilation film",2),
(235,5,'National Film Award',"Best Biographical Film","This is Best Biographical Film",2),
(236,5,'National Film Award',"Best Book On Cinema","This is Best Book On Cinema",1),
(237,5,'National Film Award',"Best Child Artiste","This is Best Child Artiste",1),
(238,5,'National Film Award',"Best Children's Film","This is Best Children's Film",2),
(239,5,'National Film Award',"Best Choreography","This is Best Choreography",1),
(240,5,'National Film Award',"Best Cinematography (Black And White)","This is Best Cinematography (Black And White)",2),
(241,5,'National Film Award',"Best Cinematography (Colour)","This is Best Cinematography (Colour)",2),
(242,5,'National Film Award',"Best Cinematography","This is Best Cinematography",2),
(243,5,'National Film Award',"Best Communication Film ( Documentary )","This is Best Communication Film ( Documentary )",2),
(244,5,'National Film Award',"Best Compilation Film","This is Best Compilation Film",2),
(245,5,'National Film Award',"Best Costume Design","This is Best Costume Design",2),
(246,5,'National Film Award',"Best Debut Non-Feature Film of A Director (Sharing)","This is Best Debut Non-Feature Film of A Director (Sharing)",2),
(247,5,'National Film Award',"Best Dialogue","This is Best Dialogue",2),
(248,5,'National Film Award',"Best Director","This is Best Director",1),
(249,5,'National Film Award',"Best Documentary Films","This is Best Documentary Films",2),
(250,5,'National Film Award',"Best Editing","This is Best Editing",2),
(251,5,'National Film Award',"Best Educational / Motivational / Instructional Film","This is Best Educational / Motivational / Instructional Film",2),
(252,5,'National Film Award',"Best Educational Film ( Documentary )","This is Best Educational Film ( Documentary )",2),
(253,5,'National Film Award',"Best Educational Film","This is Best Educational Film",2),
(254,5,'National Film Award',"Best Educational/instructional Film (Documentary)","This is Best Educational/instructional Film (Documentary)",2),
(255,5,'National Film Award',"Best Environment Film Including Agriculture","This is Best Environment Film Including Agriculture",2),
(256,5,'National Film Award',"Best Experimental Film ( Documentary )","This is Best Experimental Film ( Documentary )",2),
(257,5,'National Film Award',"Best Exploration/Adventure Film","This is Best Exploration/Adventure Film",2),
(258,5,'National Film Award',"Best Feature Film In Bengali","This is Best Feature Film In Bengali",2),
(259,5,'National Film Award',"Best Feature Film In Bhojpuri","This is Best Feature Film In Bhojpuri",2),
(260,5,'National Film Award',"Best Feature Film In English","This is Best Feature Film In English",2),
(261,5,'National Film Award',"Best Feature Film In Hindi","This is Best Feature Film In Hindi",2),
(262,5,'National Film Award',"Best Feature Film In Kannada","This is Best Feature Film In Kannada",2),
(263,5,'National Film Award',"Best Feature Film In Kokborok","This is Best Feature Film In Kokborok",2),
(264,5,'National Film Award',"Best Feature Film In Konkani","This is Best Feature Film In Konkani",2),
(265,5,'National Film Award',"Best Feature Film In Malayalam","This is Best Feature Film In Malayalam",2),
(266,5,'National Film Award',"Best Feature Film In Marathi","This is Best Feature Film In Marathi",2),
(267,5,'National Film Award',"Best Feature Film In Monpa","This is Best Feature Film In Monpa",2),
(268,5,'National Film Award',"Best Feature Film In Oriya","This is Best Feature Film In Oriya",2),
(269,5,'National Film Award',"Best Feature Film In Other Language","This is Best Feature Film In Other Language",2),
(270,5,'National Film Award',"Best Feature Film In Punjabi","This is Best Feature Film In Punjabi",2),
(271,5,'National Film Award',"Best Feature Film In Tamil","This is Best Feature Film In Tamil",2),
(272,5,'National Film Award',"Best Feature Film In Telugu","This is Best Feature Film In Telugu",2),
(273,5,'National Film Award',"Best Feature Film In Tulu","This is Best Feature Film In Tulu",2),
(274,5,'National Film Award',"Best Feature Film On Family Welfare","This is Best Feature Film On Family Welfare",2),
(275,5,'National Film Award',"Best Feature Film On National Integration","This is Best Feature Film On National Integration",2),
(276,5,'National Film Award',"Best Feature Film On The Occasion Of 25Th Anniversary Of India's Independence","This is Best Feature Film On The Occasion Of 25Th Anniversary Of India's Independence",2),
(277,5,'National Film Award',"Best Feature Film Providing Popular And Wholesome Entertainment","This is Best Feature Film Providing Popular And Wholesome Entertainment",2),
(278,5,'National Film Award',"Best Feature Film in Assamese","This is Best Feature Film in Assamese",2),
(279,5,'National Film Award',"Best Feature Film","This is Best Feature Film",2),
(280,5,'National Film Award',"Best Film Based On High Literary Work","This is Best Film Based On High Literary Work",2),
(281,5,'National Film Award',"Best Film Critic","This is Best Film Critic",2),
(282,5,'National Film Award',"Best Film Journalist","This is Best Film Journalist",2),
(283,5,'National Film Award',"Best Film On Environment/Conservation/Preservation","This is Best Film On Environment/Conservation/Preservation",2),
(284,5,'National Film Award',"Best Film On Other Social Issues","This is Best Film On Other Social Issues",2),
(285,5,'National Film Award',"Best Film On Social Issues","This is Best Film On Social Issues",2),
(286,5,'National Film Award',"Best Film Promoting National Unity And Integration","This is Best Film Promoting National Unity And Integration",2),
(287,5,'National Film Award',"Best Film Song On National Integration","This is Best Film Song On National Integration",2),
(288,5,'National Film Award',"Best Film With Social And National Purpose Theme","This is Best Film With Social And National Purpose Theme",2),
(289,5,'National Film Award',"Best Film on Sports","This is Best Film on Sports",2),
(290,5,'National Film Award',"Best Filmstrip","This is Best Filmstrip",2),
(291,5,'National Film Award',"Best First Film Of A Director","This is Best First Film Of A Director",2),
(292,5,'National Film Award',"Best First Non-Feature Film Of A Director","This is Best First Non-Feature Film Of A Director",2),
(293,5,'National Film Award',"Best Indian News Review ( Documentary )","This is Best Indian News Review ( Documentary )",2),
(294,5,'National Film Award',"Best Industrial / Agricultural Film","This is Best Industrial / Agricultural Film",2),
(295,5,'National Film Award',"Best Information Film (Documentary)","This is Best Information Film (Documentary)",2),
(296,5,'National Film Award',"Best Investigative Film","This is Best Investigative Film",2),
(297,5,'National Film Award',"Best Jury Award","This is Best Jury Award",2),
(298,5,'National Film Award',"Best Lyric-Writer Of The Best Film Song On National Integration","This is Best Lyric-Writer Of The Best Film Song On National Integration",1),
(299,5,'National Film Award',"Best Lyrics","This is Best Lyrics",1),
(300,5,'National Film Award',"Best Make-up Artist","This is Best Make-up Artist",2),
(301,5,'National Film Award',"Best Music Direction","This is Best Music Direction",2),
(302,5,'National Film Award',"Best Music","This is Best Music",1),
(303,5,'National Film Award',"Best Narration / Voice Over","This is Best Narration / Voice Over",2),
(304,5,'National Film Award',"Best National Unity And Emotional Integration","This is Best National Unity And Emotional Integration",2),
(305,5,'National Film Award',"Best News Film ( Documentary )","This is Best News Film ( Documentary )",2),
(306,5,'National Film Award',"Best News Film","This is Best News Film",2),
(307,5,'National Film Award',"Best News Review ( Documentary )","This is Best News Review ( Documentary )",2),
(308,5,'National Film Award',"Best Newsreel Cameraman ( Documentary )","This is Best Newsreel Cameraman ( Documentary )",2),
(309,5,'National Film Award',"Best Non Feature Anthropological/Ethnographic Film","This is Best Non Feature Anthropological/Ethnographic Film",2),
(310,5,'National Film Award',"Best Non Feature Film Audiography","This is Best Non Feature Film Audiography",1),
(311,5,'National Film Award',"Best Non Feature Film Cinematography","This is Best Non Feature Film Cinematography",1),
(312,5,'National Film Award',"Best Non Feature Film Editor","This is Best Non Feature Film Editor",1),
(313,5,'National Film Award',"Best Non Feature Film Music Director","This is Best Non Feature Film Music Director",1),
(314,5,'National Film Award',"Best Non Feature Film Of A Director","This is Best Non Feature Film Of A Director",1),
(315,5,'National Film Award',"Best Non Feature Film","This is Best Non Feature Film",2),
(316,5,'National Film Award',"Best Playback Singer (Female)","This is Best Playback Singer (Female)",1),
(317,5,'National Film Award',"Best Playback Singer (Male)","This is Best Playback Singer (Male)",1),
(318,5,'National Film Award',"Best Production Design","This is Best Production Design",2),
(319,5,'National Film Award',"Best Promotional Film ( Documentary )","This is Best Promotional Film ( Documentary )",2),
(320,5,'National Film Award',"Best Promotional Film - Commercial ( Documentary )","This is Best Promotional Film - Commercial ( Documentary )",2),
(321,5,'National Film Award',"Best Promotional Film - Non-Commercial","This is Best Promotional Film - Non-Commercial",2),
(322,5,'National Film Award',"Best Promotional Film","This is Best Promotional Film",2),
(323,5,'National Film Award',"Best Re-Recordist","This is Best Re-Recordist",2),
(324,5,'National Film Award',"Best Regional Feature Films","This is Best Regional Feature Films",2),
(325,5,'National Film Award',"Best Scientific Film","This is Best Scientific Film",2),
(326,5,'National Film Award',"Best Scientific/Environmental/Ecological Film","This is Best Scientific/Environmental/Ecological Film",2),
(327,5,'National Film Award',"Best Screenplay","This is Best Screenplay",2),
(328,5,'National Film Award',"Best Short Fiction Film","This is Best Short Fiction Film",2),
(329,5,'National Film Award',"Best Social Documentation Film","This is Best Social Documentation Film",2),
(330,5,'National Film Award',"Best Social Welfare/Family Welfare Film","This is Best Social Welfare/Family Welfare Film",2),
(331,5,'National Film Award',"Best Sound Recording","This is Best Sound Recording",2),
(332,5,'National Film Award',"Best Special Effects","This is Best Special Effects",2),
(333,5,'National Film Award',"Best Story","This is Best Story",2),
(334,5,'National Film Award',"Best Supporting Actor","This is Best Supporting Actor",1),
(335,5,'National Film Award',"Best Supporting Actress","This is Best Supporting Actress",1),
(336,5,'National Film Award',"Best Writing On Cinema","This is Best Writing On Cinema",2),
(337,5,'National Film Award',"Dadasaheb Phalke Award","This is Dadasaheb Phalke Award",1),
(338,5,'National Film Award',"Indira Gandhi Award For Best Debut Film Of A Director","This is Indira Gandhi Award For Best Debut Film Of A Director",1),
(339,5,'National Film Award',"Indira Gandhi Award For Best First Film Of A Director","This is Indira Gandhi Award For Best First Film Of A Director",1),
(340,5,'National Film Award',"Lyric-Writer Of The Best Film Song On National Integration","This is Lyric-Writer Of The Best Film Song On National Integration",1),
(341,5,'National Film Award',"Nargis Dutt Award For The Best Feature Film On National Integration","This is Nargis Dutt Award For The Best Feature Film On National Integration",2),
(342,5,'National Film Award',"Second Best Feature Film","This is Second Best Feature Film",2),
(343,5,'National Film Award',"Special Commendation By The Jury","This is Special Commendation By The Jury",2),
(344,5,'National Film Award',"Special Jury Award","This is Special Jury Award",1),
(345,5,'National Film Award',"Special Jury Mention","This is Special Jury Mention",1),
(346,5,'National Film Award',"Special Mention By Non-Feature Film Jury","This is Special Mention By Non-Feature Film Jury",2),
(347,5,'National Film Award',"Special Recognition","This is Special Recognition",1),
(348,5,'National Film Award',"The Jury Makes A Special Mention Of Actors","This is The Jury Makes A Special Mention Of Actors",1),
(349,6,'Stardust Award',"Actor Par Excellence","This is Actor Par Excellence",1),
(350,6,'Stardust Award',"Best Actor In An Ensemble Cast","This is Best Actor In An Ensemble Cast",1),
(351,6,'Stardust Award',"Best Actor In a Comic Role (Male)","This is Best Actor In a Comic Role (Male)",1),
(352,6,'Stardust Award',"Best Actor In a Negative Role (Male)","This is Best Actor In a Negative Role (Male)",1),
(353,6,'Stardust Award',"Best Actor In a Supporting Role","This is Best Actor In a Supporting Role",1),
(354,6,'Stardust Award',"Best Actor","This is Best Actor",1),
(355,6,'Stardust Award',"Best Actress In An Ensemble Cast","This is Best Actress In An Ensemble Cast",1),
(356,6,'Stardust Award',"Best Actress In a Supporting Role","This is Best Actress In a Supporting Role",1),
(357,6,'Stardust Award',"Best Actress","This is Best Actress",1),
(358,6,'Stardust Award',"Best Director","This is Best Director",1),
(359,6,'Stardust Award',"Best Film Award","This is Best Film Award",2),
(360,6,'Stardust Award',"Best Film Of The Year - Action/Thriller","This is Best Film Of The Year - Action/Thriller",2),
(361,6,'Stardust Award',"Best Film Of The Year - Comedy","This is Best Film Of The Year - Comedy",2),
(362,6,'Stardust Award',"Best Film Of The Year - Drama","This is Best Film Of The Year - Drama",2),
(363,6,'Stardust Award',"Best Film","This is Best Film",2),
(364,6,'Stardust Award',"Best Popular Actor Award","This is Best Popular Actor Award",1),
(365,6,'Stardust Award',"Best Popular Actress Award","This is Best Popular Actress Award",1),
(366,6,'Stardust Award',"Breakthrough Performance - Female","This is Breakthrough Performance - Female",1),
(367,6,'Stardust Award',"Breakthrough Performance - Male","This is Breakthrough Performance - Male",1),
(368,6,'Stardust Award',"Editor's Choice Award For Most Promising Director","This is Editor's Choice Award For Most Promising Director",1),
(369,6,'Stardust Award',"Editor's Choice Awards For Best Actor","This is Editor's Choice Awards For Best Actor",1),
(370,6,'Stardust Award',"Editor's Choice For The Best Director Of The Year","This is Editor's Choice For The Best Director Of The Year",1),
(371,6,'Stardust Award',"Editor's Choice For The Best Performance Of The Year","This is Editor's Choice For The Best Performance Of The Year",1),
(372,6,'Stardust Award',"Hottest Film Of The Year","This is Hottest Film Of The Year",2),
(373,6,'Stardust Award',"Hottest Film Producer","This is Hottest Film Producer",2),
(374,6,'Stardust Award',"Hottest New Director","This is Hottest New Director",1),
(375,6,'Stardust Award',"Hottest New Film","This is Hottest New Film",2),
(376,6,'Stardust Award',"Hottest Young Film Maker","This is Hottest Young Film Maker",1),
(377,6,'Stardust Award',"Lifetime Achievement Award","This is Lifetime Achievement Award",1),
(378,6,'Stardust Award',"Max Exciting New Face Award","This is Max Exciting New Face Award",1),
(379,6,'Stardust Award',"New Musical Sensation - Female","This is New Musical Sensation - Female",1),
(380,6,'Stardust Award',"New Musical Sensation - Male","This is New Musical Sensation - Male",1),
(381,6,'Stardust Award',"Outstanding Contribution To Indian Cinema","This is Outstanding Contribution To Indian Cinema",1),
(382,6,'Stardust Award',"Pride Of The Industry","This is Pride Of The Industry",1),
(383,6,'Stardust Award',"Role Model Of The Year","This is Role Model Of The Year",1),
(384,6,'Stardust Award',"Special Award","This is Special Award",1),
(385,6,'Stardust Award',"Standout Performance By A Music Director","This is Standout Performance By A Music Director",1),
(386,6,'Stardust Award',"Standout Performance By Lyricist","This is Standout Performance By Lyricist",1),
(387,6,'Stardust Award',"Standout Performance Of The Year","This is Standout Performance Of The Year",1),
(388,6,'Stardust Award',"Star Of The Year - Female","This is Star Of The Year - Female",1),
(389,6,'Stardust Award',"Star Of The Year - Male","This is Star Of The Year - Male",1),
(390,6,'Stardust Award',"Style Icon Of The Year - Female","This is Style Icon Of The Year - Female",1),
(391,6,'Stardust Award',"Style Icon Of The Year - Male","This is Style Icon Of The Year - Male",1),
(392,6,'Stardust Award',"Superstar Of Tommorow - Female","This is Superstar Of Tommorow - Female",1),
(393,6,'Stardust Award',"Superstar Of Tommorow - Male","This is Superstar Of Tommorow - Male",1),
(394,6,'Stardust Award',"The Dream Director Award","This is The Dream Director Award",1),
(395,6,'Stardust Award',"The New Menace","This is The New Menace",1),
(426,8,'Apsara Awards',"Best Actor (Female)","This is Best Actor (Female)",1),
(427,8,'Apsara Awards',"Best Actor (Male)","This is Best Actor (Male)",1),
(428,8,'Apsara Awards',"Best Actor In a Comic Role (Male)","This is Best Actor In a Comic Role (Male)",1),
(429,8,'Apsara Awards',"Best Actor In a Negative Role","This is Best Actor In a Negative Role",1),
(430,8,'Apsara Awards',"Best Actor In a Supporting Role (Female)","This is Best Actor In a Supporting Role (Female)",1),
(431,8,'Apsara Awards',"Best Actor In a Supporting Role (Male)","This is Best Actor In a Supporting Role (Male)",1),
(432,8,'Apsara Awards',"Best Actor","This is Best Actor",1),
(433,8,'Apsara Awards',"Best Actress","This is Best Actress",1),
(434,8,'Apsara Awards',"Best Art Direction","This is Best Art Direction",2),
(435,8,'Apsara Awards',"Best Choreography","This is Best Choreography",1),
(436,8,'Apsara Awards',"Best Cinematography","This is Best Cinematography",2),
(437,8,'Apsara Awards',"Best Costume Design","This is Best Costume Design",2),
(438,8,'Apsara Awards',"Best Debut (Female)","This is Best Debut (Female)",1),
(439,8,'Apsara Awards',"Best Debut (Male)","This is Best Debut (Male)",1),
(440,8,'Apsara Awards',"Best Debutant Director","This is Best Debutant Director",1),
(441,8,'Apsara Awards',"Best Dialogue","This is Best Dialogue",2),
(442,8,'Apsara Awards',"Best Director","This is Best Director",1),
(443,8,'Apsara Awards',"Best Editing","This is Best Editing",1),
(444,8,'Apsara Awards',"Best Film","This is Best Film",1),
(445,8,'Apsara Awards',"Best Lyrics","This is Best Lyrics",1),
(446,8,'Apsara Awards',"Best Music","This is Best Music",1),
(447,8,'Apsara Awards',"Best Playback Singer (Female)","This is Best Playback Singer (Female)",1),
(448,8,'Apsara Awards',"Best Playback Singer (Male)","This is Best Playback Singer (Male)",1),
(449,8,'Apsara Awards',"Best Re-Recordist","This is Best Re-Recordist",2),
(450,8,'Apsara Awards',"Best Screenplay","This is Best Screenplay",2),
(451,8,'Apsara Awards',"Best Sound Recording","This is Best Sound Recording",2),
(452,8,'Apsara Awards',"Best Special Effects","This is Best Special Effects",2),
(453,8,'Apsara Awards',"Best Story","This is Best Story",2),
(454,8,'Apsara Awards',"Cinematic Exellence (Director)","This is Cinematic Exellence (Director)",1),
(455,8,'Apsara Awards',"Cinematic Exellence (Female)","This is Cinematic Exellence (Female)",1),
(456,8,'Apsara Awards',"Cinematic Exellence (Male)","This is Cinematic Exellence (Male)",1),
(457,8,'Apsara Awards',"Entertainer of The Year Award (Female)","This is Entertainer of The Year Award (Female)",1),
(458,8,'Apsara Awards',"Entertainer of The Year Award (Male)","This is Entertainer of The Year Award (Male)",1),
(459,8,'Apsara Awards',"Lifetime Achievement Award","This is Lifetime Achievement Award",1);



/*!40000 ALTER TABLE `awards` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2011-05-14 21:01:46
